hugovk/em-keyboard

em/__init__.py
This is one of those very personal and subjectives PR… so just throw it in the garbage bin if it sounds like bullshit. The thing is that I felt this snippet could be more _pythonic_ (whatever this means):
``` python
for i, name in enumerate(names):
name = name.replace('-', '_')
name = name.replace(' ', '_')
name = name.replace('.', '_')
names[i] = name
```
Instead of redefining `name` three times, and then redefine `names[i]` I suggest to use a simpler approach: create a method to clean up names and apply it with `map` once `names` are loaded. That's what this PR is about.
I do believe current code ir more _explicit_, but I do believe the PR makes it more _beautiful_ — so you gotta choose which verse from the Zen of Python you like better ; )
=> Refactor clean name

em/__init__.py
I didn't see an obvious place that would let me update the existing `emojis.json` file, so I went ahead and added the ability myself.
Pretty simple - this will look for `~/.emojis.json` and if it's found it will update the existing emoji dictionary with the contents there. If it's not found it just does what it normally did.
I used `os.path.isfile` for no particular reason other than it's shorter apparent lines. It could've been a `try/except`, but I don't know if there's a particular reason to take that approach aside from EAFP vs. LBYL.
I'm totally happy to change this up if there's a better way to do it, but this scratches _my_ itch, so maybe it will be good for other people, too :)
=> Allow for a user ~/.emoji.json file

setup.py
Python 2.6, 3.3 and 3.4 are EOL and no longer receiving security updates (or any updates) from the core Python team.
Version | Release date | Supported until
--- | ---------- | ----------
2.6 | 2008-10-01 | 2013-10-29
2.7 | 2010-07-03 | 2020-01-01
3.0 | 2008-12-03 | 2009-06-27
3.1 | 2009-06-27 | 2012-04-09
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29
3.4 | 2014-03-16 | 2019-03-16
Source: https://en.wikipedia.org/wiki/CPython#Version_history
=> Drop support for EOL Python, add new versions

.github/workflows/deploy.yml, RELEASING.md
Deploy to TestPyPI on merges to master, to PyPI for releases.
Uses https://github.com/pypa/gh-action-pypi-publish.
I created API tokens for TestPyPI and production PyPI, and added them to the repo settings.
https://pypi.org/help/#apitoken
=> Autodeploy to PyPI

.github/workflows/deploy.yml
Re: https://github.com/pypa/gh-action-pypi-publish/commit/4425980a3392e9b685c45af290ba37dc79870af9 / https://github.com/pypa/gh-action-pypi-publish/pull/52:
> Use PYPI_API_TOKEN instead of pypi_password as secret name in examples
>
> GitHub secrets are customarily spelled in uppercase, and in PyPI terms we're dealing with API tokens here, not passwords.
=> Fix autodeploy secret names

MANIFEST.in, setup.py
```console
$ python setup.py --version
0.0.8.dev38
```
Also no need for the MANFEST.in unless we want to exclude things.
=> Use setuptools_scm to automatically get version from tag

.github/workflows/test.yml, .pre-commit-config.yaml, em/__init__.py, setup.py, tests/test_em.py
Fixes #44.
Also:
* remove mandatory xerox requirement on Linux and Windows, it's not trivially installable with pip
* test on Windows
* test on Python 3.10-dev (ahead of release in October)
=> Set encoding when opening files to fix Windows

em/__init__.py
Fixes https://github.com/hugovk/em-keyboard/issues/35.
Use `-V` or `--version` to check the version.
Uppercase `-V` as lowercase `-v` is often used for verbose.
http://www.catb.org/~esr/writings/taoup/html/ch10s05.html
```console
$ em -V
em 1.0.2.dev2
$ em --version
em 1.0.2.dev2
```
```console
$ em --help
usage: em [-h] [-s] [--no-copy] [-V] name [name ...]
em: the technicolor cli emoji keyboard™
Examples:
$ em sparkle cake sparkles
$ em heart
$ em -s food
Notes:
- If all names provided map to emojis, the resulting emojis will be
automatically added to your clipboard.
- ✨ 🍰 ✨  (sparkles cake sparkles)
positional arguments:
name           Text to convert to emoji
optional arguments:
-h, --help     show this help message and exit
-s, --search   Search for emoji
--no-copy      Does not copy …
```
=> Add version option

em/__init__.py, setup.py
Fixes #59.
pyperclip is better maintained: repo updated 7 days ago, last release Feb 21, 2021
* https://github.com/asweigart/
* https://pypi.org/project/pyperclip/
xerox: repo updated on 23 Feb 2018, last release Feb 4, 2016
* https://github.com/adityarathod/xerox
* https://pypi.org/project/xerox/
pyperclip is used for Windows copying as it's a single pip install compared to xerox.
Prioritise pyperclip over xerox.
Keep xerox as a possible copier, as we're not installing either for Linux (sub-dependencies are a bit trickier there) so allow Linux folk to whichever they may have installed.
=> Install pyperclip for macOS, prioritise over xerox

.github/workflows/deploy.yml
Follow on from https://github.com/hugovk/em-keyboard/pull/62.
`emojis.json` is generated before deploy and is committed in Git.
Fixes:
```
Run python scripts/despacify.py
Traceback (most recent call last):
File "/home/runner/work/em-keyboard/em-keyboard/scripts/despacify.py", line 7, in <module>
from em import EMOJI_PATH, parse_emojis
ModuleNotFoundError: No module named 'em'
Error: Process completed with exit code 1.
```
=> Fix deploy: no need to generate emojis.json during deploy

.github/workflows/test.yml, tox.ini
Add a test of running the CLI to prevent https://github.com/hugovk/em-keyboard/pull/65.
Failing build before that revert: 
```
cli run-test: commands[0] | em --help
Traceback (most recent call last):
File "/home/runner/work/em-keyboard/em-keyboard/.tox/cli/bin/em", line 5, in <module>
from em import cli
ModuleNotFoundError: No module named 'em'
ERROR: InvocationError for command /home/runner/work/em-keyboard/em-keyboard/.tox/cli/bin/em --help (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   cli: commands failed
Error: Process completed with exit code 1.
```
https://github.com/hugovk/em-keyboard/runs/3775745133?check_suite_focus=true
Passing build after:
```
cli run-test: commands[0] | em --help
usage: em [-h] [-s] [--no-copy] …
```
=> Test CLI is runnable

.pre-commit-config.yaml, setup.cfg, setup.py
Fixed version of https://github.com/hugovk/em-keyboard/pull/64, identical except we need to keep:
```cfg
[options]
packages = em
```
=> Setup: Use declarative metadata

em/__init__.py, setup.cfg
Profiled and visualised using https://github.com/nschloe/tuna:
```sh
python -X importtime -c 'import em; print(em.__version__)' 2> import.log
tuna import.log
```
Replacing `pkg_resources` with `importlib_metadata` shaves off about half a second, very noticeable at the command line.
=> Speedup: replace slow pkg_resources with importlib_metadata

em/__init__.py, tests/test_em.py
Right now, looking for an emoji _without_ `--search` exits 0 on success and 1 for not found:
```console
$ em one_o_clock      # exit code 0
Copied! 🕐
$ em million_o_clock  # exit code 1
$
```
But _with_ `--search` it's always exits with 0:
```console
$ em --search clock         # exit code 0
⌛  hourglass_done
⏰  alarm_clock
⏲️  timer_clock
🕰️  mantelpiece_clock
🕛  twelve_o_clock
🕐  one_o_clock
🕑  two_o_clock
🕒  three_o_clock
🕓  four_o_clock
🕔  five_o_clock
🕕  six_o_clock
🕖  seven_o_clock
🕗  eight_o_clock
🕘  nine_o_clock
🕙  ten_o_clock
🕚  eleven_o_clock
🔃  clockwise_vertical_arrows
🔄  counterclockwise_arrows_button
$ em --search clock2        # exit code 0
$
```
Instead, let's also exit with 1 when none are found:
```console
$ em --search clock2        # exit code 1
$
```
=> Exit 1 when no search results

.flake8, .github/workflows/lint.yml, .github/workflows/test.yml, .pre-commit-config.yaml, RELEASING.md, em/__init__.py, pyproject.toml, tox.ini
Changes proposed in this pull request:
* Drop support for Python 3.7, EOL this month
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0537/
* Not planning a major bump, `requires-python = ">=3.8"` makes sure people get the right version
=> Drop support for EOL Python 3.7

.github/workflows/require-pr-label.yml
The examples at https://github.com/mheap/github-action-required-labels have write permission for both issues and PRs.
This should hopefully avoid the "Approve and run" button that has started showing up for PRs after adding the changelog label.
=> Add PR write permission for github-action-required-labels

src/em_keyboard/__init__.py
Use `importlib.resources` instead of `__file__`.
This helps when creating a standalone package that includes this project.
Closes #125
=> Use `importlib.resources` instead of `__file__`

scripts/despacify.py, scripts/run_command.py, src/em_keyboard/__init__.py, tests/test_em.py
Still some more to do before adding `py.typed`.
=> Add type hints

.gitignore, pyproject.toml, src/em_keyboard/__init__.py
Like https://github.com/hugovk/tinytext/pull/195.
With Python 3.13.0rc1:
```sh
python -X importtime -c "import em_keyboard" 2> import.log && tuna import.log
```
Cuts 7 ms by removing the `importlib.metadata` import.
```console
❯ hyperfine --warmup 32 \
--prepare "git checkout rm-importlib.metadata" 'python3 -c "import em_keyboard"' \
--prepare "git checkout main"                  'python3 -c "import    em_keyboard"'
Benchmark 1: python3 -c "import em_keyboard"
Time (mean ± σ):      37.4 ms ±   1.0 ms    [User: 30.2 ms, System: 6.3 ms]
Range (min … max):    36.1 ms …  42.8 ms    64 runs
Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs.
Benchmark 2: python3 -c "import    em_keyboard"
Time (mean ± …
```
=> Generate `__version__` at build to avoid slow `importlib.metadata` import

.github/workflows/test.yml
Reduces human waiting time from 2m 57s (total machine time 13m 18s) to 1m 38s (9m 17s).
https://github.com/hugovk/em-keyboard/actions/runs/10647681519/usage
->
https://github.com/hugovk/em-keyboard/actions/runs/10647730921/usage
=> Use uv to speedup tests on CI

src/em_keyboard/__init__.py, tests/test_em.py
Implements https://github.com/hugovk/em-keyboard/issues/156
=> Allow more than one search word

README.md, pyproject.toml, src/em_keyboard/__init__.py, tests/test_em.py
This should help with https://github.com/hugovk/em-keyboard/issues/153
=> Depend on `pyperclip` on all platforms

src/em_keyboard/__init__.py, tests/test_em.py
Closes https://github.com/hugovk/em-keyboard/issues/161
=> Don't print empty line when emoji not found

src/em_keyboard/__init__.py
Some small optimisations, won't make a huge amount of difference due to the heavy `importlib` import:
* Exit early before parsing emoji
* Only import `json` and `random` if needed
* Replace `re.sub()` with `str.replace()`
=> Small optimisations

pyproject.toml
It seems that `emoji-en-US.json` is a temporary file, mostly a copy of the final despacified `emojis.json` so perhaps better to leave it out of the wheel and sdist?
This roughly halves the size of wheels built with `pipx run build`.
=> Remove temporary emoji database copy from wheel and sdist

.github/workflows/deploy.yml
Generating PyPI's digital attestations should be enough (https://docs.pypi.org/attestations/), we don't _also_ need to use https://github.com/actions/attest-build-provenance.
=> Only create PyPI digital attestations (PEP 740)

.coveragerc, pyproject.toml, tox.ini
And exclude warnings for 3.11 and lower via `.coveragerc`.
=> Use `sys.monitoring` for coverage.py

src/em/cli.py
Will be available for 3.14 beta:
https://docs.python.org/3.14/library/argparse.html#color
=> Enable colour help for Python 3.14
