hugovk/em-keyboard

- em/__init__.py
I couldn't work out why `-s` was so slow! It looks like there was a loop inside a loop that wasn't necessary. I can't find any difference in behaviour with this fix, but it is many, many times faster.🔁 ➿
> Unneeded outer-loop.

- em/emojis.json
Update `emojis.json` so that we can use newer emojis. 🤣 👩‍🎨 🦌
> Update emojis.json to emoijlib v2.2.1

- .gitignore
- README.md
- em/__init__.py
- setup.py
- tests.py
- tox.ini
Same as https://github.com/inishchith/em-keyboard/pull/14 (and therefore closes #14) but rebased on master and merge conflicts resolved.
> Rebased: Tests ❤️

- em/__init__.py
- tests/test_em.py
And convert from unittest to pytest, remove some Python 2 code, and an unused function.
> Add more tests

- aliases.json
> Remove unused aliases.json, feature was removed in 2016

- setup.py
> Use correct platform_system for Windows

- em/__init__.py
- tests/test_em.py
```console
$ em Sparkles shortcaKe SPARKLES
$ em -s Medal
$ 
```
```console
$ em Sparkles shortcaKe SPARKLES
Copied! ✨ 🍰 ✨
$ em -s Medal
🎖️  military_medal
🏅  sports_medal
🥇  1st_place_medal
🥈  2nd_place_medal
🥉  3rd_place_medal
$ 
```
> Allow mixed-case input

- .github/workflows/test.yml
This reverts commit 2dc21de756200e6316e836b7a4607ee718b17d23.
https://github.com/actions/setup-python/issues/328#issuecomment-1030025436
> Revert "Temporarily use actions/setup-python@v2.3.2 to fix Windows"

- .github/workflows/deploy.yml
- .github/workflows/labels.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- README.md
- em/__init__.py
- scripts/run_command.py
- tests/test_em.py
- tox.ini
```console
$ em -s ukraine
🇺🇦  flag_ukraine
```
```console
$ em -s ukraine
Copied! 🇺🇦  flag_ukraine
```
Also:
* Use https://github.com/nedbat/cog to keep README examples updated
* Bump https://github.com/actions/checkout to v3
* Refactor `sys.exit` mock into `pytest.raises`; earlier it continued running past the mocked `sys.exit`
* Also generate coverage HTML output via tox
> If there's only a single search result, copy it

- pyproject.toml
Currently in alpha, full release due on 2023-10-02.
https://peps.python.org/pep-0693/
> Add support for Python 3.12

- .github/workflows/deploy.yml
- .github/workflows/require-pr-label.yml
Re: https://github.com/hynek/build-and-inspect-python-package
> Use hynek/build-and-inspect-python-package

- README.md
- src/em_keyboard/__init__.py
There is no trademark here, as far as I'm aware.
> Remove trademark symbol

- tests/test_em.py
Test random with no copy.
Test supplying no name.
> Additional tests

- .coveragerc
- .flake8
- .github/labels.yml
- .github/renovate.json
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- scripts/run_command.py
- src/em_keyboard/__init__.py
- tests/test_em.py
And add Prettier and update some other config.
> Replace Flake8 with Ruff

- .github/renovate.json
https://docs.renovatebot.com/semantic-commits/
> Renovate: Disable conventional commits

- .github/workflows/test.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/em_keyboard/__init__.py
- tox.ini
It will be end-of-life in about a month:
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0569/
* https://endoflife.date/python
> Drop support for Python 3.8

- .github/workflows/deploy.yml
- .github/workflows/labels.yml
- .github/workflows/lint.yml
- .github/workflows/release-drafter.yml
- .github/workflows/test.yml
And replace pre-commit/action with faster tox-dev/action-pre-commit-uv.
> Fix zizmor findings on CI

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
https://woodruffw.github.io/zizmor/audits/#excessive-permissions
Also use https://github.com/astral-sh/setup-uv and set `RUFF_OUTPUT_FORMAT` for linting.
> Fix warning[excessive-permissions]: overly broad permissions

- pyproject.toml
Follow on from https://github.com/hugovk/em-keyboard/pull/167.
> Require hatchling>=1.27 for licence expressions (PEP 639)

- .coveragerc
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/release-drafter.yml
- .github/workflows/test.yml
- pyproject.toml
> Test PyPy3.11
